import torch
import sys
import os
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline,
)
from peft import PeftModel

# --- Configuration ---
# Your local model folder generated by the training script
MODEL_DIR = "./health_myth_checker_tinylama/final_merged_model"
# The base model used for fine-tuning
BASE_MODEL_ID = "TinyLlama/TinyLlama-1.1B-Chat-v1.0" 

# --- 1. Define the Inference Function ---
def check_claim_locally(claim_text):
    """Loads the fine-tuned model and generates a health check verdict."""
    
    # We no longer need to determine 'device' explicitly, device_map='auto' handles it.
    
    # 1. Load the tokenizer and model
    try:
        # Load tokenizer from the original base model for stability
        tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
        
        # Load the merged model (in float16 for efficiency)
        print("--- Loading Model Weights into Memory (May take 1-2 mins) ---")
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_DIR, # Load from your local merged folder
            torch_dtype=torch.float16,
            device_map="auto" # CRITICAL: Let accelerate handle device placement
        )
        
    except Exception as e:
        print(f"\n❌ Error loading model components. Make sure the folder '{MODEL_DIR}' exists.")
        print(f"Error details: {e}")
        return

    # 2. Format the Input Prompt
    prompt = (
        "## Health Claim Checker\n\n"
        f"### Claim\n{claim_text}\n\n"
        "### Response\n"
    )

    # 3. Create the Inference Pipeline
    # The simplest possible pipeline call, relying on loaded model and tokenizer objects.
    pipe = pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        # Removed all arguments that caused conflicts (device, etc.)
        max_new_tokens=400, 
        temperature=0.1,    
        top_k=10,
        repetition_penalty=1.1,
    )

    # 4. Generate the Response
    print("--- Running Inference ---")
    result = pipe(prompt)
    
    # 5. Extract and print the formatted response text
    full_response = result[0]['generated_text']
    
    # Clean the response to only show the model's output after "### Response\n"
    if '### Response\n' in full_response:
        response_text = full_response.split('### Response\n', 1)[1].strip()
    else:
        # Fallback if the model didn't perfectly follow the prompt
        response_text = full_response.strip()

    print("\n" + "="*50)
    print(f"Checking Claim: '{claim_text}'")
    print("="*50)
    print(response_text)
    print("="*50 + "\n")


# --- 2. Execution ---
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python check_model.py \"<Your health claim here>\"")
        print("\nExample: python check_model.py \"Does drinking lemon water cure all inflammation?\"")
        sys.exit(1)
        
    claim = sys.argv[1]
    check_claim_locally(claim)