import torch
import sys
import os
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline,
)
from peft import PeftModel

# --- Configuration ---
# Your local model folder generated by the training script
MODEL_DIR = "./health_myth_checker_tinylama/final_merged_model"
# The base model used for fine-tuning
BASE_MODEL_ID = "TinyLlama/TinyLlama-1.1B-Chat-v1.0" 

# --- 1. Define the Inference Function ---
def check_claim_locally(claim_text):
    """Loads the fine-tuned model and generates a health check verdict."""
    
    # Check if GPU is available
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    
    if device == "cpu":
        print("⚠️ Warning: CUDA not detected. Running inference on CPU, which will be slow.")

    # 1. Load the tokenizer and model
    try:
        tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
        
        # Load the base model (in float16 for efficiency)
        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL_ID,
            torch_dtype=torch.float16,
            device_map="auto"
        )
        
        # Load the merged model (which should already contain the adapter)
        # We load the weights saved from the merge step (final_merged_model)
        # Note: If the final_merged_model is a full model, this step might not be strictly needed,
        # but loading the tokenizer from the final folder ensures correctness.

    except Exception as e:
        print(f"\n❌ Error loading model components. Make sure the folder '{MODEL_DIR}' exists.")
        print(f"Error details: {e}")
        return

    # 2. Format the Input Prompt
    # This MUST match the structured format used in your training data (health_myth_data.jsonl)
    prompt = (
        "## Health Claim Checker\n\n"
        f"### Claim\n{claim_text}\n\n"
        "### Response\n"
    )

    # 3. Create the Inference Pipeline
    pipe = pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        device=device,
        max_new_tokens=400, # Max length of the response
        temperature=0.1,    # Low temperature for stable, factual output
        top_k=10,
        repetition_penalty=1.1,
    )

    # 4. Generate the Response
    result = pipe(prompt)
    
    # 5. Extract and print the formatted response text
    response_text = result[0]['generated_text'].split('### Response\n')[1].strip()
    
    print("\n" + "="*50)
    print("✅ HEALTH CHECK VERDICT")
    print("="*50)
    print(response_text)
    print("="*50 + "\n")


# --- 2. Execution ---
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python check_local_myth.py \"<Your health claim here>\"")
        print("\nExample: python check_local_myth.py \"Eating only fruit for a week will detoxify my body.\"")
        sys.exit(1)
        
    claim = sys.argv[1]
    check_claim_locally(claim)